In [4]:
import numpy as np

In [11]:
# buat matrix X berukuran 2x3 menggunakan numpy
x = np.array([[25, 15, 61],
              [54, 45, 25]])
x

array([[25, 15, 61],
       [54, 45, 25]])

In [12]:
# tampilkan ukuran dari matrix X
x.shape

(2, 3)

In [17]:
# tampilkan seluruh elemen dari kolom pertama dari matrix X
x[:,0]

array([25, 54])

In [18]:
# tampilkan seluruh elemen dari baris kedua dari matrix X
x[1,:]

array([54, 45, 25])

In [19]:
# ulangi soal nomor 1 menggunakan pytorch
import torch

In [25]:
# buat matrix X berukuran 2x3 menggunakan pytorch
x_pt = torch.tensor([[15, 54, 25],
              [25, 61, 54]])
x_pt

tensor([[15, 54, 25],
        [25, 61, 54]])

In [26]:
# tampilkan ukuran dari matrix X
x_pt.shape

torch.Size([2, 3])

In [27]:
# tampilkan seluruh elemen dari kolom pertama dari matrix X
x_pt[:,0]

tensor([15, 25])

In [28]:
# tampilkan seluruh elemen dari baris kedua dari matrix X
x_pt[1,:]

tensor([25, 61, 54])

In [29]:
# ulangi soal nomor 1 menggunakan tensorflow
import tensorflow as tf

In [30]:
# buat matrix X berukuran 2x3 menggunakan tensorflow
x_tf = tf.Variable([[55, 54, 25],
                    [61, 15, 54]])
x_tf

<tf.Variable 'Variable:0' shape=(2, 3) dtype=int32, numpy=
array([[55, 54, 25],
       [61, 15, 54]], dtype=int32)>

In [31]:
# tampilkan ukuran dari matrix X
tf.shape(x_tf)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([2, 3], dtype=int32)>

In [33]:
# tampilkan seluruh elemen dari kolom pertama dari matrix X
x_tf[:,0]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([55, 61], dtype=int32)>

In [34]:
# tampilkan seluruh elemen dari baris kedua dari matrix X
x_tf[1,:]

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([61, 15, 54], dtype=int32)>