In [2]:
import numpy as np

In [3]:
# buat vector x dengan ukuran 3x1
x = np.array([54, 5, 4])
x

array([54,  5,  4])

In [4]:
# hitung panjang vector x
len(x)

3

In [5]:
# tampilkan ukuran vector x
x.shape

(3,)

In [6]:
# tampilkan tipe data dari vector x
type (x)

numpy.ndarray

In [7]:
# akses elemen pertama dari vector x
x[0]

np.int64(54)

In [8]:
# tampilkan tipe data elemen pertama dari vector x
type (x[0])

numpy.int64

In [9]:
# lakukan transpose pada vector x dan simpan pada variabel x_t
x_t = x.T
x_t

array([54,  5,  4])

In [10]:
# tampilkan ukuran dari vector x_t
x_t.shape

(3,)

In [13]:
# buat vector y dengan ukuran 3x1
y = np.array([[45, 4, 5]])
y

array([[45,  4,  5]])

In [14]:
# lakukan transpose pada vector y dan simpan pada variabel y_t
y_t = y.T
y_t

array([[45],
       [ 4],
       [ 5]])

In [15]:
# tampilkan ukuran dari vector y_t
y_t.shape

(3, 1)

In [1]:
# lakukan soal nomor 2 menggunakan pytorch dan tensorflow
import torch
import tensorflow as tf

In [7]:
y_pt = torch.tensor([54, 61, 4])
y_pt

tensor([54, 61,  4])

In [6]:
y_tf = tf.Variable([61, 5, 4])
y_tf

<tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([61,  5,  4], dtype=int32)>

In [8]:
# lakukan transpose pada vector y_pt dan simpan pada variabel y_pt_t
y_pt_t = y_pt.T
y_pt_t

tensor([54, 61,  4])

In [12]:
# lakukan transpose pada vector y_tf dan simpan pada variabel y_tf_t
y_tf_t = tf.transpose(y_tf)
y_tf_t

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([61,  5,  4], dtype=int32)>

In [13]:
# tampilkan ukuran dari vector y_pt_t
y_pt_t.shape

torch.Size([3])

In [14]:
# tampilkan ukuran dari vector x_tf_t
y_tf_t.shape

TensorShape([3])